[tox]
envlist =
    py{310,311,312,313,314}-flask3
    py{310,311,312,313,314}-socialmaster

[testenv]
passenv = *
allowlist_externals =
  uv
install_command = uv pip install --no-binary lxml --no-binary xmlsec {opts} {packages}
commands =
    coverage run -m pytest tests/
deps =
    flask3: Flask>=3.0,<4.0
    socialmaster: https://github.com/python-social-auth/social-core/archive/master.tar.gz
    .[dev]
    pytest
